Added a new file with a homework to the lesson_14
eugene-okulik/Elena- pull request #15
Opened 2024-08-08 15:05 UTC by ElenaSi-m

2024-08-08 15:12 UTC, eugene-okulik requested changes
В базе данных больше тысячи студентов уже создано. Вряд ли твой студент добавился под id 269, групп там создано тоже больше тысячи или, как минимум, около того. Вряд ли твой группа добавилась под id 179.  
Ну и нужно выполнить задание в той последовательности, как написано в задании.

2024-08-08 15:12 UTC, eugene-okulik commented on homework/elena_sinitsina/lesson_14/homework_lesson14.sql
> +INSERT INTO "groups"(title , start_date , end_date) VALUES('Beginners','June24','Sep24')
В задании было 

> 1. Создайте студента (student)
> 2. Создайте несколько книг (books) и укажите, что ваш созданный студент взял их
> 3. Создайте группу (group) и определите своего студента туда

А я вижу выполнение так:
1. Создайте студента с установленной группой
2. Добавьте группу

Но ведь группы еще нет...

2024-08-08 16:44 UTC, ElenaSi-m commented
Please look at 2 files with screenshots: when I did this yesterday I only got numbers 264, 275 ... etc . But when I opened my file today again and refreshed - I got all the numbers 1000 + . I updated my file already And I'm not sure how it could happened.

2024-08-09 00:30 UTC, ElenaSi-m commented
If I understand there are few databases, so maybe I used another one in the first case ?

2024-08-09 08:05 UTC, eugene-okulik approved these changes
Да, на скриншоте видно, что ты под пользователем st_onl пользуешься не базой st_onl, а базой st4

2024-08-09 08:05 UTC, merged