Added new project Test_final_api_esinitsina
eugene-okulik/Elena- pull request #24
Opened 2024-09-17 14:19 UTC by ElenaSi-m

2024-09-17 15:10 UTC, ElenaSi-m commented
Не совсем понятно как проверять, что прошлый токен рабочий : только хардкодить ? Т.е. проверяем токен который у меня был сгенерирован последний раз?

2024-09-18 08:42 UTC, eugene-okulik commented
> Не совсем понятно как проверять, что прошлый токен рабочий : только хардкодить ? Т.е. проверяем токен который у меня был сгенерирован последний раз?

Это не обязательная проверка. Но если хочется между запусками пользоваться одним и тем же токеном, и менять его только когда он перестал работать, то токен можно сохранять где-то в текстовом файле.

2024-09-18 08:51 UTC, eugene-okulik requested changes
1. В этой API больше чем 3 ендпоинта, а у тебя всего 3 теста
2. Проект нужно было создавать в отдельном репозитории. Вот здесь можно посмотреть как создавать репозитории: https://youtu.be/MpNGAU9J4vw?si=LlPtu9lFmFKEjm6E
3. В задании было: "Внимание! Именно тестируем АПИ. Не проверяем каждый эндпоинт одним тестом, а тестируем, чтобы убедиться, что АПИ работает правильно в различных сценариях." Для тестирования этой API нужно порядка 80-100 тестов. Столько не нужно, но хотя бы по несколько тестов на каждый ендпоинт нужно сделать. Вот видео о том, что можно тестировать в апи: https://youtu.be/CU5hrXYRCRk?si=GyfjV8l6lj7E4rAl  
В предыдущих заданиях мы тренировались создавать правильную структуру тестов, проекта. В этом задании мы пишем автотесты.

2024-09-18 08:51 UTC, eugene-okulik commented on homework/elena_sinitsina/test_final_api_esinitsina/tests/test_meme_management.py
> +    create_meme_endpoint.check_response_info_is_correct(data["info"])
Здесь ты проверяешь только что информация из info созранилась правильно. Но в этом тесте нам будет важно, что все данные сохранились правильно.

2024-09-18 08:51 UTC, eugene-okulik commented on homework/elena_sinitsina/test_final_api_esinitsina/tests/test_meme_management.py
> +    assert update_meme_endpoint.json.get('text') == payload['text']
Здесь ты проверяешь только одно поле. Но здесь нам нужно убедиться, что то, что мы изменяли, изменилось, а то, что не изменяли, не изменилось.

2025-05-07 18:37 UTC, closed without merging