Added 2 files with homework from lesson_6
eugene-okulik/Elena- pull request #7
Opened 2024-07-11 18:47 UTC by ElenaSi-m

2024-07-11 18:57 UTC, ElenaSi-m commented
Could you please check

2024-07-12 07:46 UTC, eugene-okulik requested changes

2024-07-12 08:41 UTC, ElenaSi-m commented
Fixed! Thank you

2024-07-12 08:49 UTC, eugene-okulik approved these changes

2024-07-12 08:49 UTC, eugene-okulik commented on homework/elena_sinitsina/lesson_6/homework_2_lesson6.py
> +        print(x)
Нуу, как вариант, но можно было сделать всё без избыточных условий:
```python
for x in range(1, 101):
    if x % 3 == 0 and x % 5 == 0:
        print('FuzzBuzz')
    elif x % 5 == 0:
        print('Buzz')
    elif x % 3 == 0:
        print('Fuzz')
    else:
        print(x)
```

2024-07-12 08:50 UTC, merged