Added 2 new files with homework to the lesson_8
eugene-okulik/Elena- pull request #9
Opened 2024-07-17 19:08 UTC by ElenaSi-m

2024-07-17 19:14 UTC, ElenaSi-m commented
In the last task I changed the number 100000th (removed one 0) because it showed mistake about limit. Check the svreenshot attached.
![messageImage_1721242392984](https://github.com/user-attachments/assets/bdbd91ca-09e2-45b1-a8c3-8ca414bf9e0e)

2024-07-18 08:34 UTC, eugene-okulik commented
> In the last task I changed the number 100000th (removed one 0) because it showed mistake about limit. Check the screenshot attached. ![messageImage_1721242392984](https://private-user-images.githubusercontent.com/174484117/349643844-bdbd91ca-09e2-45b1-a8c3-8ca414bf9e0e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTE4MjEsIm5iZiI6MTcyMTI5MTUyMSwicGF0aCI6Ii8xNzQ0ODQxMTcvMzQ5NjQzODQ0LWJkYmQ5MWNhLTA5ZTItNDViMS1hOGMzLThjYTQxNGJmOWUwZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQwODMyMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTQ0MzY1YzQxNmNlMTkxYTIwNzgwZDViOTQ1OGQ0NDM5ZDdiYTFkOWI1NDA5NWQ4ZDM0YTYxY2NlOWEyOWY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ni5ExmrUracienmTDqRfEn_M5glI4IE-8n6GHY0iKcE)

Здесь ладно, сойдет. Но вообще нужно не изменять условия задания под выполнение, а делать выполнение таким, чтобы оно соответствовало заданию.  
В идеале, было бы поискать решение как сделать так, чтобы это работало с тем числом, которое указано в задании.

2024-07-18 08:42 UTC, eugene-okulik requested changes
Одна из целей использования генераторов заключается в том, чтобы не приходилось большие объемы данных держать одновременно в памяти компьютера. А сохранение каждого числа фибоначчи в список как раз создает большой объем данных, хотя в каждый конкретный момент тебе весь список не нужен, а нужен всего один элемент из него.  
Нужно, получая числа от генератора, распечатать те, которые нужны по условиям задания.

2024-07-18 14:14 UTC, ElenaSi-m commented
Doshlo.... All fixed

2024-07-18 15:21 UTC, eugene-okulik approved these changes
:+1:

2024-07-18 15:23 UTC, merged